version: "3.9"
services:
  web:
    build: .
    hostname: server
    volumes:
      - /Users/sulaiman/Projects/experiments/nginx/0-base.conf:/etc/httpd/conf.d/0-base.conf
      - /Users/sulaiman/Projects/experiments/nginx/1-zeh.conf:/etc/httpd/conf.d/1-zeh.conf
      - /Users/sulaiman/Projects/experiments/nginx/base:/var/www/html/base
      - /Users/sulaiman/Projects/experiments/nginx/entry.sh:/opt/entrypoint.sh
    expose: ["8888", "9999"]
    entrypoint:
      - bash
      - /opt/entrypoint.sh
  
  nginx:
    image: nginx:latest
    hostname: nginx
    depends_on: [web]
    volumes:
      - /Users/sulaiman/Projects/experiments/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 7777:80