version: '3.9'
services:
  geth:
    image: core-geth:latest
    hostname: geth
    # entrypoint: ["geth", "--mintme", "--nodiscover", "--maxpeers", "0", "--http", "--http.addr", "0.0.0.0", "--ws", "--ws.addr", "0.0.0.0"] #, "--nat", "extip:0.0.0.0"]
    entrypoint: geth --mintme --nodiscover --maxpeers 0 --http --http.addr geth  --ws --ws.addr geth #, "--nat", "extip:0.0.0.0"]
    volumes:
      - /Users/sulaiman/Projects/experiments/crypto/geth_ethereum:/root/.ethereum/
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
      - 30303:30303/udp

  redis:
    image: redis:latest
    hostname: redis
    volumes:
      - /Users/sulaiman/Projects/experiments/crypto/redis.conf:/opt/redis.conf
      # - /Users/sulaiman/Projects/experiments/crypto/dump.rdb:/data/dump.rdb
    entrypoint: ["redis-server", "/opt/redis.conf"]
    ports:
      - 6379:6379

  webchaind:
    image: ubuntu:18.04
    hostname: webchaind
    depends_on:
      - geth
      - redis
    volumes:
      - /Users/sulaiman/Projects/experiments/crypto/webchain:/root/.webchain/
      - /Users/sulaiman/Projects/experiments/crypto/webchaind:/opt/webchaind
      - /Users/sulaiman/Projects/experiments/crypto/wallet.pass:/root/wallet.pass
    entrypoint: /opt/webchaind --nodiscover --mine --rpc --rpcaddr 0.0.0.0 --unlock '0x5547084b1a0eab05af2bd8d15464279c320c7114' --password /root/wallet.pass
    ports:
      - 39573:39573

  # webchain-pool:
  #   image: ubuntu:18.04
  #   hostname: webchain-pool
  #   depends_on:
  #     - webchaind
  #   volumes:
  #     - /Users/sulaiman/Projects/experiments/crypto/pool-config.json:/opt/config.json
  #     - /Users/sulaiman/Projects/experiments/crypto/pool/:/opt/pool/
  #     - /Users/sulaiman/Projects/experiments/crypto/environment.js:/opt/pool/www/config/environment.js
  #   entrypoint: /opt/pool/build/bin/webchain-pool /opt/config.json
  #   ports:
  #     - 8080:8080
  #     - 8888:8888
  #     - 3333:3333

  webchain-pool:
    image: crypto/webchain-pool:0.2
    hostname: webchain-pool
    depends_on: 
      - webchaind
    volumes:
      - /Users/sulaiman/Projects/experiments/crypto/pool-config.json:/opt/config.json
      - /Users/sulaiman/Projects/experiments/crypto/pool/:/opt/pool/
      - /Users/sulaiman/Projects/experiments/crypto/environment.js:/opt/pool/www/config/environment.js
      - /Users/sulaiman/Projects/experiments/crypto/pool.sh:/opt/pool.sh
      - /Users/sulaiman/Projects/experiments/crypto/nginx.conf:/etc/nginx/sites-available/default
    # entrypoint: ["/bin/bash", "-c", "/opt/pool/build/bin/webchain-pool", "/opt/config.json"]
    # entrypoint: ["/opt/pool/build/bin/webchain-pool", "/opt/config.json"]
    # command: ["/opt/pool/build/bin/webchain-pool", "/opt/config.json"]
    command: ["bash", "/opt/pool.sh"]
    ports:
      - 8080:8080
      - 8888:8888
      - 3333:3333
      - 9090:80

  xmrig:
    image: crypto/xmrig:xmrig
    hostname: xmrig
    depends_on:
      - webchain-pool
    volumes:
      - /Users/sulaiman/Projects/experiments/crypto/xmrig-config2.json:/usr/local/bin/config.json
    # entrypoint: xmrig -k

  # nginx:
  #   image: nginx:latest
  #   hostname: nginx
  #   # depends_on:
  #   #   - webchain-pool
  #   volumes:
  #     - /Users/sulaiman/Projects/experiments/crypto/pool/:/opt/pool/
  #     - /Users/sulaiman/Projects/experiments/crypto/nginx.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - 9090:80
